# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ѡ��.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
import sys
import os
from PyQt4 import QtGui
from PyQt4 import QtCore
from data_write import *
import main
import future
today_name = u'v3.0选股' + today + u'.xlsx'

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s
def abc():
    print 123
    print 34
try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):
    def def__init__(self, parent =None):
        QtGui.QMainWindow.__init__(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1250, 760)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("image/icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_0 = QtGui.QGridLayout()
        self.gridLayout_0.setMargin(50)
        self.gridLayout_0.setSpacing(10)
        self.gridLayout_0.setObjectName(_fromUtf8("gridLayout_0"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_0.addLayout(self.gridLayout_5, 1, 1, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_0.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_0.addLayout(self.gridLayout_8, 2, 1, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_0.addLayout(self.gridLayout_6, 1, 2, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_0.addLayout(self.gridLayout_7, 2, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_0.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_0.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_1 = QtGui.QGridLayout()
        self.gridLayout_1.setObjectName(_fromUtf8("gridLayout_1"))
        self.gridLayout_0.addLayout(self.gridLayout_1, 0, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.commandLinkButton = QtGui.QCommandLinkButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton.setAutoDefault(False)
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.gridLayout_9.addWidget(self.commandLinkButton, 0, 0, 1, 1)
        self.gridLayout_0.addLayout(self.gridLayout_9, 2, 2, 1, 1)
        self.gridLayout_0.setColumnMinimumWidth(0, 225)
        self.gridLayout_0.setColumnMinimumWidth(1, 500)
        self.gridLayout_0.setColumnMinimumWidth(2, 225)
        self.gridLayout_0.setRowMinimumHeight(0, 100)
        self.gridLayout_0.setRowMinimumHeight(1, 200)
        self.gridLayout_0.setRowMinimumHeight(2, 100)
        self.gridLayout_0.setColumnStretch(0, 2)
        self.gridLayout_0.setColumnStretch(1, 3)
        self.gridLayout_0.setColumnStretch(2, 2)
        self.gridLayout_0.setRowStretch(0, 2)
        self.gridLayout_0.setRowStretch(1, 3)
        self.gridLayout_0.setRowStretch(2, 2)
        self.verticalLayout.addLayout(self.gridLayout_0)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 12)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1250, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_1 = QtGui.QMenu(self.menubar)
        self.menu_1.setObjectName(_fromUtf8("menu_1"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menu_4 = QtGui.QMenu(self.menubar)
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        self.menu_5 = QtGui.QMenu(self.menubar)
        self.menu_5.setObjectName(_fromUtf8("menu_5"))
        self.menu_6 = QtGui.QMenu(self.menubar)
        self.menu_6.setObjectName(_fromUtf8("menu_6"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_all = QtGui.QAction(MainWindow)
        self.action_all.setObjectName(_fromUtf8("action_all"))
        self.action_EXCEL = QtGui.QAction(MainWindow)
        self.action_EXCEL.setObjectName(_fromUtf8("action_EXCEL"))
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_1 = QtGui.QAction(MainWindow)
        self.action_1.setObjectName(_fromUtf8("action_1"))
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.action_3 = QtGui.QAction(MainWindow)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.action_4 = QtGui.QAction(MainWindow)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action_15 = QtGui.QAction(MainWindow)
        self.action_15.setObjectName(_fromUtf8("action_15"))
        self.action_16 = QtGui.QAction(MainWindow)
        self.action_16.setObjectName(_fromUtf8("action_16"))
        self.action_17 = QtGui.QAction(MainWindow)
        self.action_17.setObjectName(_fromUtf8("action_17"))
        self.action_18 = QtGui.QAction(MainWindow)
        self.action_18.setObjectName(_fromUtf8("action_18"))
        self.action_19 = QtGui.QAction(MainWindow)
        self.action_19.setObjectName(_fromUtf8("action_19"))
        self.action_202122 = QtGui.QAction(MainWindow)
        self.action_202122.setObjectName(_fromUtf8("action_202122"))
        self.action_23 = QtGui.QAction(MainWindow)
        self.action_23.setObjectName(_fromUtf8("action_23"))
        self.action_5 = QtGui.QAction(MainWindow)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.action_6 = QtGui.QAction(MainWindow)
        self.action_6.setObjectName(_fromUtf8("action_6"))
        self.action_7 = QtGui.QAction(MainWindow)
        self.action_7.setObjectName(_fromUtf8("action_7"))
        self.action_8 = QtGui.QAction(MainWindow)
        self.action_8.setObjectName(_fromUtf8("action_8"))
        self.action_9 = QtGui.QAction(MainWindow)
        self.action_9.setObjectName(_fromUtf8("action_9"))
        self.action_10 = QtGui.QAction(MainWindow)
        self.action_10.setObjectName(_fromUtf8("action_10"))
        self.action_11 = QtGui.QAction(MainWindow)
        self.action_11.setObjectName(_fromUtf8("action_11"))
        self.action_12 = QtGui.QAction(MainWindow)
        self.action_12.setObjectName(_fromUtf8("action_12"))
        self.action_13 = QtGui.QAction(MainWindow)
        self.action_13.setObjectName(_fromUtf8("action_13"))
        self.action_14 = QtGui.QAction(MainWindow)
        self.action_14.setObjectName(_fromUtf8("action_14"))
        self.action_24 = QtGui.QAction(MainWindow)
        self.action_24.setObjectName(_fromUtf8("action_24"))
        self.action_25 = QtGui.QAction(MainWindow)
        self.action_25.setObjectName(_fromUtf8("action_25"))
        self.action_27 = QtGui.QAction(MainWindow)
        self.action_27.setObjectName(_fromUtf8("action_27"))
        self.action_operation = QtGui.QAction(MainWindow)
        self.action_operation.setObjectName(_fromUtf8("action_operation"))
        self.action_strategy = QtGui.QAction(MainWindow)
        self.action_strategy.setObjectName(_fromUtf8("action_strategy"))
        self.action_graph = QtGui.QAction(MainWindow)
        self.action_graph.setObjectName(_fromUtf8("action_graph"))
        self.action_future = QtGui.QAction(MainWindow)
        self.action_future.setObjectName(_fromUtf8("action_future"))
        self.menu_1.addAction(self.action_all)
        self.menu_1.addAction(self.action_EXCEL)
        self.menu_1.addSeparator()
        self.menu_1.addAction(self.action_exit)
        self.menu_2.addAction(self.action_1)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menu_3.addAction(self.action_15)
        self.menu_3.addAction(self.action_16)
        self.menu_3.addAction(self.action_17)
        self.menu_3.addAction(self.action_18)
        self.menu_3.addAction(self.action_19)
        self.menu_3.addAction(self.action_202122)
        self.menu_3.addAction(self.action_23)
        self.menu_3.addAction(self.action_27)
        self.menu_4.addAction(self.action_5)
        self.menu_4.addAction(self.action_6)
        self.menu_4.addAction(self.action_7)
        self.menu_4.addAction(self.action_8)
        self.menu_4.addAction(self.action_9)
        self.menu_4.addAction(self.action_10)
        self.menu_4.addAction(self.action_11)
        self.menu_4.addAction(self.action_12)
        self.menu_4.addAction(self.action_13)
        self.menu_4.addAction(self.action_14)
        self.menu_4.addAction(self.action_24)
        self.menu_4.addAction(self.action_25)
        self.menu_5.addAction(self.action_operation)
        self.menu_5.addAction(self.action_strategy)
        self.menu_6.addAction(self.action_graph)
        self.menu_6.addAction(self.action_future)
        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    # def action_2(self):
    #     QtGui.QMessageBox.about( self, u'写入成功', u'营收季增率提高策略已经成功，请点击打开进行浏览' )

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "选股V3.0", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":image/title.png\"/></p></body></html>", None))
        self.commandLinkButton.setText(_translate("MainWindow", "打开股票池", None))
        self.menu_1.setTitle(_translate("MainWindow", "文件", None))
        self.menu_2.setTitle(_translate("MainWindow", "公司价值", None))
        self.menu_3.setTitle(_translate("MainWindow", "筹码分布", None))
        self.menu_4.setTitle(_translate("MainWindow", "市场波动", None))
        self.menu_5.setTitle(_translate("MainWindow", "帮助说明", None))
        self.menu_6.setTitle(_translate("MainWindow", "趋势图", None))
        self.action_all.setText(_translate("MainWindow", "执行所有策略", None))
        self.action_EXCEL.setText(_translate("MainWindow", "打开EXCEL", None))
        self.action_exit.setText(_translate("MainWindow", "退出", None))
        self.action_1.setText(_translate("MainWindow", "营收季增率", None))
        self.action_2.setText(_translate("MainWindow", "EPS季增率", None))
        self.action_3.setText(_translate("MainWindow", "毛利率季增率", None))
        self.action_4.setText(_translate("MainWindow", "ROE季增率", None))
        self.action_15.setText(_translate("MainWindow", "融资余额", None))
        self.action_16.setText(_translate("MainWindow", "户均持股", None))
        self.action_17.setText(_translate("MainWindow", "股东户数", None))
        self.action_18.setText(_translate("MainWindow", "十大股东变化数量", None))
        self.action_19.setText(_translate("MainWindow", "十大股东持股比例", None))
        self.action_202122.setText(_translate("MainWindow", "券商、基金、机构持股", None))
        self.action_23.setText(_translate("MainWindow", "换手率", None))
        self.action_5.setText(_translate("MainWindow", "波动率", None))
        self.action_6.setText(_translate("MainWindow", "价格", None))
        self.action_7.setText(_translate("MainWindow", "日周月10MA", None))
        self.action_8.setText(_translate("MainWindow", "日线10MA", None))
        self.action_9.setText(_translate("MainWindow", "周线10MA", None))
        self.action_10.setText(_translate("MainWindow", "月线10MA", None))
        self.action_11.setText(_translate("MainWindow", "波动区间", None))
        self.action_12.setText(_translate("MainWindow", "60天波动区间", None))
        self.action_13.setText(_translate("MainWindow", "180天波动区间", None))
        self.action_14.setText(_translate("MainWindow", "250天波动区间", None))
        self.action_24.setText(_translate("MainWindow", "涨幅超过大盘", None))
        self.action_25.setText(_translate("MainWindow", "袁氏选股(积极版+年版)", None))
        self.action_27.setText(_translate("MainWindow", "股本", None))
        self.action_operation.setText(_translate("MainWindow", "操作说明", None))
        self.action_strategy.setText(_translate("MainWindow", "策略说明", None))
        self.action_graph.setText(_translate("MainWindow", "趋势图（股票）", None))
        self.action_future.setText(_translate("MainWindow", "趋势图（期货）", None))

        self.commandLinkButton.clicked.connect(self.execute)
        self.action_EXCEL.triggered.connect(self.execute)
        self.action_all.triggered.connect(self.strategy_all)
        self.action_1.triggered.connect(self.strategy1)
        self.action_2.triggered.connect(self.strategy2)
        self.action_3.triggered.connect(self.strategy3)
        self.action_4.triggered.connect(self.strategy4)
        self.action_5.triggered.connect(self.strategy5)
        self.action_6.triggered.connect(self.strategy6)
        self.action_7.triggered.connect(self.strategy7)
        self.action_8.triggered.connect(self.strategy8)
        self.action_9.triggered.connect(self.strategy9)
        self.action_10.triggered.connect(self.strategy10)
        self.action_11.triggered.connect(self.strategy11)
        self.action_12.triggered.connect(self.strategy12)
        self.action_13.triggered.connect(self.strategy13)
        self.action_14.triggered.connect(self.strategy14)
        self.action_15.triggered.connect(self.strategy15)
        self.action_16.triggered.connect(self.strategy16)
        self.action_17.triggered.connect(self.strategy17)
        self.action_18.triggered.connect(self.strategy18)
        self.action_19.triggered.connect(self.strategy19)
        self.action_202122.triggered.connect(self.strategy202122)
        self.action_23.triggered.connect(self.strategy23)
        self.action_24.triggered.connect(self.strategy24)
        self.action_25.triggered.connect(self.strategy25)
        self.action_27.triggered.connect(self.strategy27)
        self.action_operation.triggered.connect(self.guide)
        self.slavewindow = slaveWindow()
        self.action_strategy.triggered.connect(self.slavewindow.show)
        self.action_exit.triggered.connect(self.exit)
        self.action_graph.triggered.connect(self.graph)
        self.action_future.triggered.connect(self.future)

        #调整窗口打开的位置
        screen = QtGui.QDesktopWidget().screenGeometry()
        size = self.geometry()
        self.move((screen.width() - size.width()) / 2, (screen.height() - size.height()) / 2)
    def strategy1(self):
        strategy1()
        QtGui.QMessageBox.about( self, u'写入成功', u'营收季增率提高策略已经成功，请点击打开进行浏览' )
    def strategy2(self):
        strategy2()
        QtGui.QMessageBox.about( self, u'写入成功', u'EPS季增率提高策略已经成功，请点击打开进行浏览' )
    def strategy3(self):
        strategy3()
        QtGui.QMessageBox.about( self, u'写入成功', u'毛利率季增率提高策略已经成功，请点击打开进行浏览' )
    def strategy4(self):
        strategy4()
        QtGui.QMessageBox.about( self, u'写入成功', u'ROE季增率提高策略已经成功，请点击打开进行浏览' )
    def strategy5(self):
        strategy5()
        QtGui.QMessageBox.about( self, u'写入成功', u'波动率策略已经成功，请点击打开进行浏览' )
    def strategy6(self):
        strategy6()
        QtGui.QMessageBox.about( self, u'写入成功', u'价格策略已经成功，请点击打开进行浏览' )
    def strategy7(self):
        strategy7()
        QtGui.QMessageBox.about( self, u'写入成功', u'日周月10MA策略已经成功，请点击打开进行浏览' )
    def strategy8(self):
        strategy8()
        QtGui.QMessageBox.about( self, u'写入成功', u'日线10MA策略已经成功，请点击打开进行浏览' )
    def strategy9(self):
        strategy9()
        QtGui.QMessageBox.about( self, u'写入成功', u'周线10MA策略已经成功，请点击打开进行浏览' )
    def strategy10(self):
        strategy10()
        QtGui.QMessageBox.about( self, u'写入成功', u'月线10MA策略已经成功，请点击打开进行浏览' )
    def strategy11(self):
        strategy11()
        QtGui.QMessageBox.about( self, u'写入成功', u'波动区间策略已经成功，请点击打开进行浏览' )
    def strategy12(self):
        strategy12()
        QtGui.QMessageBox.about( self, u'写入成功', u'60天波动区间策略已经成功，请点击打开进行浏览' )
    def strategy13(self):
        strategy13()
        QtGui.QMessageBox.about( self, u'写入成功', u'180天波动区间策略已经成功，请点击打开进行浏览' )
    def strategy14(self):
        strategy14()
        QtGui.QMessageBox.about( self, u'写入成功', u'250天波动区间策略已经成功，请点击打开进行浏览' )
    def strategy15(self):
        strategy15()
        QtGui.QMessageBox.about( self, u'写入成功', u'融资余额策略已经成功，请点击打开进行浏览' )
    def strategy16(self):
        strategy16()
        QtGui.QMessageBox.about( self, u'写入成功', u'户均持股策略已经成功，请点击打开进行浏览' )
    def strategy17(self):
        strategy17()
        QtGui.QMessageBox.about( self, u'写入成功', u'股东户数策略已经成功，请点击打开进行浏览' )
    def strategy18(self):
        strategy18()
        QtGui.QMessageBox.about( self, u'写入成功', u'十大股东变化数量策略已经成功，请点击打开进行浏览' )
    def strategy19(self):
        strategy19()
        QtGui.QMessageBox.about( self, u'写入成功', u'十大股东持股比例策略已经成功，请点击打开进行浏览' )
    def strategy202122(self):
        strategy202122()
        QtGui.QMessageBox.about( self, u'写入成功', u'券商、基金、机构持股策略已经成功，请点击打开进行浏览' )
    def strategy23(self):
        strategy23()
        QtGui.QMessageBox.about( self, u'写入成功', u'换手率策略已经成功，请点击打开进行浏览' )
    def strategy24(self):
        strategy24()
        QtGui.QMessageBox.about( self, u'写入成功', u'涨幅超过大盘策略已经成功，请点击打开进行浏览' )
    def strategy25(self):
        strategy25()
        QtGui.QMessageBox.about(self, u'写入成功', u'袁氏选股策略已经成功，请点击打开进行浏览')
    def strategy27(self):
        strategy27()
        QtGui.QMessageBox.about(self, u'写入成功', u'股本资料写入已经成功，请点击打开进行浏览')
    def strategy_all(self):
        QtGui.QMessageBox.about( self, u'开始执行', u'执行所有策略耗时较长，点击确定开始，请耐心等待' )
        all_strategy()
        QtGui.QMessageBox.about( self, u'写入成功', u'所有策略已经成功，请点击打开进行浏览' )

    def indro(self):
        f = open(u"策略说明.txt","r")
        text = f.read()
        text = unicode(text, "utf8")
        QtGui.QMessageBox.about(self, u'策略说明', text)
        # os.getcwd()
        # x = u'策略说明.txt'
        # os.system(x.encode('gbk'))

    def guide(self):
        f = open(u"操作说明.txt","r")
        text = f.read()
        text = unicode(text,"utf8")
        QtGui.QMessageBox.about(self, u'操作说明', text)
        f.close()
    def execute(self):
        os.getcwd()
        os.system(today_name.encode('gbk'))
    def exit(self):
        sys.exit(app.exec_())
    def graph(self):
        self.graph = main.ApplicationWindow()
        self.graph.show()
    def future(self):
        self.future = future.ApplicationWindow()
        self.future.show()
class slaveWindow(QtGui.QWidget):
    def __init__(self, parent = None):
        super(slaveWindow, self).__init__(parent)
        f = open(u"策略说明.txt", "r")
        text = f.read()
        text = unicode(text, "utf8")
        self.widget = QtGui.QWidget(self)
        self.label = QtGui.QLabel(self.widget)
        self.label.setText(_translate("MainWindow", text, None))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.addWidget(self.label)
        self.setWindowTitle(_translate("MainWindow", "策略说明", None))
        self.resize(900,600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("image/icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        pe = QtGui.QPalette()
        pe.setColor(QtGui.QPalette.Background, QtGui.QColor(0,0,0))
        self.label.setPalette(pe)
app = QtGui.QApplication(sys.argv)
qt = Ui_MainWindow()
qt.setupUi(qt)
qt.show()
sys.exit(app.exec_())
